---
- hosts: other
  remote_user: ansible
  become: yes
  vars:
   - user: tutu
   - utilisateur:
       - tete
       - tyty
       - tutu

  tasks:
    - name: Utilisation de debug
      become: yes
      debug: msg= "{{ item }}"
      with_file:
        - first_file
        - second_file

    - name: creation des utilisateur
      become: yes
      user:
        name: '{{ item }}'
        createhome: yes
        state: present
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        comment: 'User create via ansible'
        password: iwlg|J39R
      with_items:
        - '{{ utilisateur }}'
...
