---
- hosts: other
  become: yes
  remote_user: ansible
  vars:
    date_time: "{{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"

  tasks:
  - name: write date run to a file in the server
    template:
      src: /etc/ansible/templates/date_templates.j2
      dest: /home/ansible/date-time.txt
    register: tempdate
    tags:
      - datetemplate
...
